name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "1 1 * * 1"

permissions:
  contents: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install go pkgs
        run: |
          go mod download

      - name: Test
        run: |
          make test

      - name: Bench
        run: |
          make bench | tee benchmark_result.txt

      - name: Continuous Benchmark
        uses: benchmark-action/github-action-benchmark@v1.16.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: Go Benchmark
          tool: "go"
          output-file-path: benchmark_result.txt
          github-token: ${{ secrets.CI_TOKEN }}
          gh-repository: "github.com/ringsaturn/benchmark4fun"
          auto-push: true
          alert-threshold: "500%"
          comment-on-alert: true
          fail-on-alert: false
          benchmark-data-dir-path: "docs/"
          alert-comment-cc-users: "@ringsaturn"

  build-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: nightly
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run benches
      run: cargo bench --verbose
